# Site settings
title: Art By Marie
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Art by Marie
baseurl: ""
url: "http://www.artbymarie.info"

collections:
  watercolours:
    output: true
  oils:
    output: true

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
